name: Merge code
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to merge to master
        type: string
        required: true
        default: feature1  
      # Name:
      #   description: Select name
      #   type: choice
      #   options:
      #     - Toan
      #     - Tran
      # Print_tag:
      #   description: Print to STDOUT
      #   required: true
      #   type: boolean
      # environment:
      #   description: Choose environment
      #   required: true
      #   type: environment
env:
  TEST: abc
jobs:
    merge:
      runs-on: ubuntu-latest

      steps:
        - name: checkout source code
          uses: actions/checkout@v4
          with:
            ref: master
            path: master

        - name: merge code
          id: merge_code
          uses: devmasx/merge-branch@1.4.0
          with:
            type: now
            from_branch: ${{ inputs.branch }}
            target_branch: master
            github_token: ${{ secrets.GITHUB_TOKEN }}
          continue-on-error: true
        - name: OutputOK
          if: steps.merge_code.outputs.merged == 'true'
          run: echo "OK"
        - name: OutputNOOK
          if: steps.merge_code.outputs.merged == 'false'
          run: | 
            echo "NOT OK"
            echo "Message: ${{ steps.merge_branch.outputs.message }}"
            echo "merged: ${{ steps.merge_branch.outputs.merged }}"
            echo "outcome: ${{ steps.merge_branch.outcome }}"
        

          
      
