name: CI/CD

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write  # Give permission to generate ID token for authentication
      contents: read   # Read permissions to fetch the repository content
      actions: read    # Read permission for actions metadata (for debugging purposes)

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Log in to Azure using Service Principal
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Login to ACR
    - name: Log in to Azure Container Registry (ACR)
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.ACR_REGISTRY_NAME }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    # Build and push the Docker image to ACR
    - name: Build and Push Docker image to ACR
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: ${{ secrets.ACR_REGISTRY_NAME }}/my-image:latest
        build-args: |
          DB_INFO=QA
    
    - name: Set AKS context
      id: set-context
      uses: azure/aks-set-context@v3
      with:
        resource-group: '${{ secrets.AZURE_RESOURCE_GROUP }}'
        cluster-name: '${{ secrets.AZURE_CLUSTER_NAME }}'
    
    - name: Setup kubectl
      id: install-kubectl
      uses: azure/setup-kubectl@v3

    - name: update variable from secrets
      run: |
        sed -i 's|NAME_VALUE|'"$(echo "${{ secrets.NAME }}" deployment.yaml
    
    - name: Deploy to AKS
      id: deploy-aks
      uses: Azure/k8s-deploy@v4
      with:
        namespace: 'default'
        manifests: |
          deployment.yaml
        images: |
          '${{ secrets.ACR_REGISTRY_NAME }}/my-image:latest

    # - name: Copy image from dev to qa ACR
    #   run: |
    #     az acr import --name mycontainerregistrydemoqa \
    #         --source ${{ secrets.ACR_REGISTRY_NAME }}/hello-world:latest \
    #         --image hello-world:latest

