name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
        type: string

jobs:

  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Call test_workflow
      uses: ./.github/workflows/test_workflow.yaml
