name: Matrix Workflow

on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Choose server (a or b)'
        required: true
        default: 'a'
        type: choice
        options:
          - a
          - b
      job:
        description: 'Choose job'
        required: true
        default: 'job1'
        type: choice
        options:
          - all
          - job1
          - job2

jobs:
  job1:
    if: inputs.job == 'all' || inputs.job == github.job
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      SERVER: ${{ github.event.inputs.server == 'a' && 'abc' || 'bcd' }}
    strategy:
      matrix:
        task: 
          - task1
          - task2
          - task3
      fail-fast: false
      max-parallel: 1
    steps:
      - name: Echo task name in ${{ env.SERVER }} and job name is ${{ github.job }}
        run: echo "Running ${{ matrix.task }}"
  job2:
    if: inputs.job == 'all' || inputs.job == github.job
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      SERVER: ${{ github.event.inputs.server == 'a' && 'abc' || 'bcd' }}
    strategy:
      matrix:
        task: 
          - task1
          - task2
          - task3
      fail-fast: false
      max-parallel: 1
    steps:
      - name: Echo task name in ${{ env.SERVER }} and job name is ${{ github.job }}
        run: echo "Running ${{ matrix.task }}"
    
