name: Matrix Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [task1, task2]
    steps:
      - name: Echo task name
        run: echo "Running ${{ matrix.task }}"

      - name: Fail for task1
        if: ${{ matrix.task == 'task1' }}
        run: exit 1

    timeout-minutes: 30
