name: Matrix Workflow

on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Choose server (a or b)'
        required: true
        default: 'a'
        type: choice
        options:
          - a
          - b
      job:
        description: 'Choose job'
        required: true
        default: 'job1'
        type: choice
        options:
          - all
          - job1
          - job2
jobs:
  job1:
    if: inputs.job == 'all' || inputs.job == 'job1'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Echo task name
        run: exit 0
  job2:
    if: inputs.job == 'all' || inputs.job == 'job2' 
    needs: job1
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Echo task name
        run: sleep 60
  job3:
    if: ( !cancelled() ) && (inputs.job == 'all' || inputs.job == 'job3')
    needs: job2
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: job name is ${{ github.job }}
        run: sleep 60 && echo "Done"
  job4:
    if: always()
    needs: job1
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: job name is ${{ needs.job1.result }}
        run: echo "Success ${{ needs.job1.result }}"
  