name: Test workflow

on:
  workflow_call:
    inputs:
      name:
        description: Name
        type: string
        required: true
        default: Toan


jobs:
  BUILD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Just print
        run: |
          echo "Hello ${{ inputs.name }}"