name: test

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      status:
        description: 'status of do something'
        type: number
        default: 0

jobs:
  TEST:
    env:
      ID: 1
      STATUS: "OK"
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0
      
      # - name: Get Latest Tag
      #   id: get_tag
      #   # You may pin to the exact commit or the version.
      #   # uses: WyriHaximus/github-action-get-previous-tag@04e8485ecb6487243907e330d522ff60f02283ce
      #   uses: WyriHaximus/github-action-get-previous-tag@v1
      # - name: Print the tag
      #   run: |
      #     echo "Tag is: ${{ steps.get_tag.outputs.tag }}"
      - name: Do something
        id: dosomething
        continue-on-error: true
        run: |
          exit ${{ inputs.status }}

      - name: Handle OK
        if: steps.dosomething.outcome == 'success'
        run: |
          echo "ID=2" >> $GITHUB_ENV
          echo "STATUS=OK" >> $GITHUB_ENV
      - name: Hanle NOT OK
        if: steps.dosomething.outcome == 'failure'
        run: |
          echo "ID=1" >> $GITHUB_ENV
          echo "STATUS=NOT OK" >> $GITHUB_ENV
      - name: Update something
        run: |
          echo "ID is: ${{ ID }} , STATUS: ${{ STATUS }}"
      # - uses: olegtarasov/get-tag@v2.1.3
      #   id: tagName

      # - name: Some other step # Output usage example
      #   run: |
      #     echo "tagname: ${{ steps.tagName.outputs.tag }}"
      #     echo "tag from variable: $GIT_TAG_NAME"
  # TEST2:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Just echo
  #       run: |
  #        echo "Hello from Test 2"
  #     - name: Echo2
  #       run: |
  #         echo "Echo 2"
          
