name: Test workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: Name
        type: string
        required: true
        default: Toan

jobs:
  BUILD:
    runs-on: [self-hosted, windows]
    steps:
      - name: Just print
        run: |
          echo "Hello ${{ inputs.name }}"